platform :ios, '15.4'

target 'iosApp' do
  use_frameworks!
     pod 'MapLibre', '6.17.1'
  # Pods for iosApp
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.4'
    end
  end
end